### ISSUE TITLE
fix awsmobile init problem

### ISSUE THREAD

**Issue by edzillion** [CirclesUBI/circles-mobile#16]
I describe the problem here: https://github.com/aws/awsmobile-cli/issues/180

It seems the very simple fix is to remove the `awsmobilejs` folder - I wish this was documented somewhere :disappointed: 

I have tested on my setup and one other, I am going to try to set up @ronitronitronit this afternoon.

**Comment by edzillion** [comment]
Ok just setup  @ronitronitronit :clap: and works fine with here. I am gonna merge this branch.

**Comment by ronitronitronit** [comment]
It doesn't work fine... I'll look into it over the weekend.

**Comment by edzillion** [comment]
What doesn't work fine @ronitronitronit ? The point of these notes is that we explain things!

Can you post your error message etc? thanks

**Comment by ronitronitronit** [comment]
Will follow up tonight! :)
