### ISSUE TITLE
Create unit tests for circles-mobile

### ISSUE THREAD

**Issue by innsmouthrain** [CirclesUBI/circles-mobile#25]
- Creating tests, starting with lib/reducers
- first, populating tests with all obvious cases,
- should then require a critical group review on wtf we're doing
- finalizing with a good idea of what's up and 
- leaving with a sensible approach and more knowledge to continue the testing endeavour

**Comment by edzillion** [comment]
We have gone for an integration test style route and I don't think unit tests will fit into our timeline so I am closing this for now,
