### ISSUE TITLE
Invariant Violation: Text strings must be rendered within a <Text> component - when deleting the content of a TextInput

### ISSUE THREAD

**Issue by edzillion** [CirclesUBI/circles-mobile#28]
To reproduce:

Open the app and choose sign up. Any text input will work, just write some text and then delete it, when there is no text the app crashes with above error. 

I looked this up last night and found many indirect suggestions, like removing whitespace and importing packages, not sure about this case. Could be a bug with the updated packages I am using on the `cognito-auth` branch

**Comment by shkfnly** [comment]
fixed in #46
