### ISSUE TITLE
Signup flow work. Photo upload before signUp / key submission

### ISSUE THREAD

**Issue by edzillion** [CirclesUBI/circles-mobile#33]
The signUp flow goes like this:

1. OnboardingTerms
2. OnboardingAvatar <-- user adds name and submits photo which is immediately uploaded & replaced by url
3. OnboardingPhone <-- user adds phone & email
4. OnboardingVerifyPhone <-- email, phone, name, picture and deviceId are sent to `signUp()`. Code sent by calling `confirmSignUp`
5. OnboardingTestnet <-- I think this point will create the users public / private keys?
6. OnboardingComplete

Currenrly, the userpool requires name, email, phone, picture & custom:deviceId - since picture is required that means that on calling `signUp()`  it requires something to be submitted for it. 

We could unset picture as required and upload it after confirmation? 

How does this fit in with key creation / uploading?

**Comment by shkfnly** [comment]
I think this has already been resolved
