### ISSUE TITLE
MacOS build issues

### ISSUE THREAD

**Issue by edzillion** [CirclesUBI/circles-mobile#83]
Can't get the app to work on iOS with xcode:

```
expo start
cd ios
pod install
[xcode] build for emulator (iphone x)
...
[xcode] Build Succeeded
...
[expo-cli] Building Javascript bundle 100%
...
WARNING: Missing strong random number source; using weak randomBytes
Shims Injected:
  - atob
  - btoa
  - nextTick
Running application on iPhone X.
[INFO] 08:02.415 App - Initializing ...
```
aaaaaand that's where it stalls.

**Comment by edzillion** [comment]
I checked the log viewer on macOS but there is no errors and nothing stands out.

**Comment by shkfnly** [comment]
pod install before expo start

**Comment by edzillion** [comment]
That made no difference. Still just a whitescreen and no errors.

**Comment by eminx** [comment]
I can confirm that I've bumped into exactly same issue trying to setup locally on my Mac.

It's `[INFO] 24:49.7 App - Initializing ...`

and white screen...

@shkfnly Could you please assist? Thanks!

**Comment by eminx** [comment]
OK it was apparently the fonts that prevented the render.
