### ISSUE TITLE
error: too many arguments in interface function signup

### ISSUE THREAD

**Issue by edzillion** [CirclesUBI/circles-mobile#84]
> [ERROR] 38:07.242 Auth Saga [Error: too many arguments in interface function signup (count=2, expectedCount=1, version=4.0.27)]

I think this line needs to be updated to work with the current contract:

`const data = HubContract.interface.functions.signup.encode([senderKeyPair.address, cognitoUser.username])`

**Comment by ana0** [comment]
This method needs to be changed to `relayerSignup`

**Comment by edzillion** [comment]
Ok I now get 

`[ERROR] 45:42.18 Auth Saga [Error: invalid response - 0]`

Which is the same as the (perhaps still blocking) problem before.

**Comment by ana0** [comment]
You mean the one you've had since forever?

**Comment by edzillion** [comment]
yeah :(
